### ISSUE TITLE
Can't export image

### ISSUE THREAD

**Issue by mti1313** [SynBioDex/SBOLCanvas#267] opened 2023-11-14 18:52 UTC
Export image fails with "This Page isn't Working" Error 500.

**Comment by PhysicsTeacher13** [comment] 2023-11-17 14:22
problem still persists 

![failed_img_3](https://github.com/SynBioDex/SBOLCanvas/assets/22648782/04f18bce-783e-4d2d-980a-cbc39c70c2cf)

**Comment by cjmyers** [comment] 2023-11-21 23:45
Could you provide a screenshot of SBOLCanvas when you try to do this?  It is working for me, so I'm not sure if there is something unique about your circuit design.

**Comment by mmcdonald1575** [comment] 2023-11-22 20:58
I am also having this problem. It is difficult to take a screenshot because the error message opens in a new window and SBOLCanvas returns to the design screen with no other messages or indicators.

**Comment by mmcdonald1575** [comment] 2023-11-22 21:06
I have taken a screen recording of this happening, but the file is too big to attach in GitHub. I would be happy to email it to the MSEE support account if necessary. I have also alerted the TA, Isha about the issue.

**Comment by cjmyers** [comment] 2023-11-22 23:25
Sorry for the trouble.  Could you perhaps post a link to a Google Drive or similar where we can find the recording.

**Comment by mmcdonald1575** [comment] 2023-11-22 23:38
I can definitely do that. Is a link to google drive preferred over emailing
the .mp4?

**Comment by cjmyers** [comment] 2023-11-22 23:40
Yes, thanks

**Comment by mmcdonald1575** [comment] 2023-11-22 23:50
Here is the link. The file is held in my UC Boulder Drive (mimc6837). Just
throwing that out there to deter confusion when it isn't this email address.

https://drive.google.com/file/d/1a9FoiaVDLXcl4gf60-XKSeRNIavz27GR/view?usp=drive_link

Thanks,
Mitch

**Comment by cjmyers** [comment] 2023-11-28 22:05
The best workaround right now is to take a screenshot of your circuit and turn that it.  It is essentially the same thing as if the export image was working.  Sorry for your trouble.  We are trying to work out the bug, but it will still take a bit.

**Comment by mmcdonald1575** [comment] 2023-11-28 22:07
Ok, no problem. Thanks for letting me know.

**Comment by cjmyers** [comment] 2023-12-13 02:19
I think we finally have been able to upgrade SBOLCanvas.  If any of you get a chance to try again, please report on whether the errors you have seen are fixed or not.  Thanks.  Sorry for the inconvenience.

**Comment by rcmb** [comment] 2024-01-18 03:19
Image export still failing. Attempted on Edge and Chrome.

![image](https://github.com/SynBioDex/SBOLCanvas/assets/26347646/f845972e-2c6b-41db-9c86-aba10b697d99)

**Comment by cjmyers** [comment] 2024-02-08 23:12
We are not able to reproduce this error.  Does Export->File work?  If so, can you send your file?  Could you also provide a screenshot of your SBOLCanvas page?  Can you reproduce this?  If so, can you explain the steps that you took?

**Comment by rcmb** [comment] 2024-02-09 01:55
File Export works for me.

![image](https://github.com/SynBioDex/SBOLCanvas/assets/26347646/cfc55f1b-f7fc-40ff-9cbb-7ff6745ac869)

**Workflow**

1. File > Export Image
2. Type "A1Image" as the filename
3. Select format as "PNG"
4. Click "Export"
5. Page navigates to "https://[canvas-api.greensky-6cc75ee4.westus.azurecontainerapps.io](https://canvas-api.greensky-6cc75ee4.westus.azurecontainerapps.io/api/export)/api/export" and throws below error:

This page isn’t working right nowcanvas-api.greensky-6cc75ee4.westus.azurecontainerapps.io can't currently handle this request.

**Comment by cjmyers** [comment] 2024-02-09 21:15
Thanks.  I can reproduce your error.  I will look into it.

If you are doing this for the Coursera course, you can submit your screenshot for the assignment.

**Comment by rcmb** [comment] 2024-02-10 16:34
Thank you. I removed the file from my comment above.

**Comment by cjmyers** [comment] 2024-02-10 21:51
Further debugging found that if I remove the two terminators, the image is generated.  It looks like image generation has a problem with hierarchical parts.

**Comment by cjmyers** [comment] 2024-03-21 23:29
This is fixed now

**Closed as completed by cjmyers** 2024-03-21 23:29 UTC
