### ISSUE TITLE
Part names are not visible on glyphs

### ISSUE THREAD

**Issue by kevinwkeating** [SynBioDex/SBOLCanvas#41] opened 2020-01-16 21:18 UTC
When glyphs are dragged onto canvas and the name field is changed in the Info tab, the new names do not appear next to the part.

**Comment by SamuelSauce** [comment] 2020-04-19 17:30
@cjmyers @Randoom97 I don't know if it was intended functionality to have the name of the part appear on the canvas, perhaps that was what the text box is for? If this is the case we could either mark this as an 'Enhancement' and take off the 'bug' label, or we could close the issue as this can be achieved with a text box.

**Closed as completed** 2020-05-20 20:45 UTC
Labels: bug
